//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPVWPF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TPVWPF.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección:.
        /// </summary>
        public static string AddressLabel {
            get {
                return ResourceManager.GetString("AddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar al Carrito.
        /// </summary>
        public static string AddToCartButtonText {
            get {
                return ResourceManager.GetString("AddToCartButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir al carrito.
        /// </summary>
        public static string AddToCartButtonTextDetail {
            get {
                return ResourceManager.GetString("AddToCartButtonTextDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string CancelButtonTextEdit {
            get {
                return ResourceManager.GetString("CancelButtonTextEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrito.
        /// </summary>
        public static string CartButtonText {
            get {
                return ResourceManager.GetString("CartButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrito de Compras.
        /// </summary>
        public static string CartViewTitle {
            get {
                return ResourceManager.GetString("CartViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogo.
        /// </summary>
        public static string CatalogButtonText {
            get {
                return ResourceManager.GetString("CatalogButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogo de Productos.
        /// </summary>
        public static string CatalogViewTitle {
            get {
                return ResourceManager.GetString("CatalogViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string CheckoutViewTitle {
            get {
                return ResourceManager.GetString("CheckoutViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ganancia del Mes Actual:.
        /// </summary>
        public static string CurrentMonthRevenueLabel {
            get {
                return ResourceManager.GetString("CurrentMonthRevenueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección:.
        /// </summary>
        public static string CustomerAddressLabel {
            get {
                return ResourceManager.GetString("CustomerAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos del Cliente.
        /// </summary>
        public static string CustomerDetailsLabel {
            get {
                return ResourceManager.GetString("CustomerDetailsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre:.
        /// </summary>
        public static string CustomerFirstNameLabel {
            get {
                return ResourceManager.GetString("CustomerFirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información del Cliente.
        /// </summary>
        public static string CustomerInformationHeader {
            get {
                return ResourceManager.GetString("CustomerInformationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido:.
        /// </summary>
        public static string CustomerLastNameLabel {
            get {
                return ResourceManager.GetString("CustomerLastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Método de Pago:.
        /// </summary>
        public static string CustomerPaymentMethodLabel {
            get {
                return ResourceManager.GetString("CustomerPaymentMethodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string DateColumnHeader {
            get {
                return ResourceManager.GetString("DateColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string DeleteButtonText {
            get {
                return ResourceManager.GetString("DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Producto.
        /// </summary>
        public static string DeleteProductButtonText {
            get {
                return ResourceManager.GetString("DeleteProductButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Producto.
        /// </summary>
        public static string EditProductButtonText {
            get {
                return ResourceManager.GetString("EditProductButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay productos en el carrito.
        /// </summary>
        public static string EmptyCartMessage {
            get {
                return ResourceManager.GetString("EmptyCartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar PDF.
        /// </summary>
        public static string ExportInvoiceButton {
            get {
                return ResourceManager.GetString("ExportInvoiceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizar Compra.
        /// </summary>
        public static string FinalizePurchaseButtonText {
            get {
                return ResourceManager.GetString("FinalizePurchaseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string FirstNameColumnHeader {
            get {
                return ResourceManager.GetString("FirstNameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre:.
        /// </summary>
        public static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir al Checkout.
        /// </summary>
        public static string GoToCheckoutButtonText {
            get {
                return ResourceManager.GetString("GoToCheckoutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ganancia Total Histórica:.
        /// </summary>
        public static string HistoricalTotalRevenueLabel {
            get {
                return ResourceManager.GetString("HistoricalTotalRevenueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma:.
        /// </summary>
        public static string LanguageLabelSettings {
            get {
                return ResourceManager.GetString("LanguageLabelSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string LastNameColumnHeader {
            get {
                return ResourceManager.GetString("LastNameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido:.
        /// </summary>
        public static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de Sesión.
        /// </summary>
        public static string LoginViewTitle {
            get {
                return ResourceManager.GetString("LoginViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPV Tienda de Música.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrar Productos.
        /// </summary>
        public static string ManageProductsButtonText {
            get {
                return ResourceManager.GetString("ManageProductsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Producto.
        /// </summary>
        public static string NewProductButtonText {
            get {
                return ResourceManager.GetString("NewProductButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles del Pedido.
        /// </summary>
        public static string OrderDetailViewTitle {
            get {
                return ResourceManager.GetString("OrderDetailViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumen del Pedido.
        /// </summary>
        public static string OrderSummaryLabel {
            get {
                return ResourceManager.GetString("OrderSummaryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total del Pedido:.
        /// </summary>
        public static string OrderTotalLabel {
            get {
                return ResourceManager.GetString("OrderTotalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña:.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Método de Pago:.
        /// </summary>
        public static string PaymentMethodLabel {
            get {
                return ResourceManager.GetString("PaymentMethodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración de Productos.
        /// </summary>
        public static string ProductAdminViewTitle {
            get {
                return ResourceManager.GetString("ProductAdminViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría.
        /// </summary>
        public static string ProductCategoryColumnHeader {
            get {
                return ResourceManager.GetString("ProductCategoryColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría:.
        /// </summary>
        public static string ProductCategoryLabelEdit {
            get {
                return ResourceManager.GetString("ProductCategoryLabelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string ProductDescriptionColumnHeader {
            get {
                return ResourceManager.GetString("ProductDescriptionColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción:.
        /// </summary>
        public static string ProductDescriptionLabelEdit {
            get {
                return ResourceManager.GetString("ProductDescriptionLabelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría:.
        /// </summary>
        public static string ProductDetailCategoryLabel {
            get {
                return ResourceManager.GetString("ProductDetailCategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción:.
        /// </summary>
        public static string ProductDetailDescriptionLabel {
            get {
                return ResourceManager.GetString("ProductDetailDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio:.
        /// </summary>
        public static string ProductDetailPriceLabel {
            get {
                return ResourceManager.GetString("ProductDetailPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Detalles.
        /// </summary>
        public static string ProductDetailsButtonText {
            get {
                return ResourceManager.GetString("ProductDetailsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles del Producto.
        /// </summary>
        public static string ProductEditViewTitle {
            get {
                return ResourceManager.GetString("ProductEditViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ProductIdColumnHeader {
            get {
                return ResourceManager.GetString("ProductIdColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string ProductNameColumnHeader {
            get {
                return ResourceManager.GetString("ProductNameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre:.
        /// </summary>
        public static string ProductNameLabelEdit {
            get {
                return ResourceManager.GetString("ProductNameLabelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        public static string ProductPriceColumnHeader {
            get {
                return ResourceManager.GetString("ProductPriceColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio:.
        /// </summary>
        public static string ProductPriceLabelEdit {
            get {
                return ResourceManager.GetString("ProductPriceLabelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reportes.
        /// </summary>
        public static string ReportsButtonText {
            get {
                return ResourceManager.GetString("ReportsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informes y Estadísticas.
        /// </summary>
        public static string ReportsViewTitle {
            get {
                return ResourceManager.GetString("ReportsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historial de Ventas.
        /// </summary>
        public static string SalesHistoryButtonText {
            get {
                return ResourceManager.GetString("SalesHistoryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historial de Ventas.
        /// </summary>
        public static string SalesHistoryViewTitle {
            get {
                return ResourceManager.GetString("SalesHistoryViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string SaveButtonTextEdit {
            get {
                return ResourceManager.GetString("SaveButtonTextEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string SaveButtonTextSettings {
            get {
                return ResourceManager.GetString("SaveButtonTextSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        public static string SettingsButtonText {
            get {
                return ResourceManager.GetString("SettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        public static string SettingsViewTitle {
            get {
                return ResourceManager.GetString("SettingsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string TotalColumnHeader {
            get {
                return ResourceManager.GetString("TotalColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string TotalLabelText {
            get {
                return ResourceManager.GetString("TotalLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad Total de Productos:.
        /// </summary>
        public static string TotalProductsLabel {
            get {
                return ResourceManager.GetString("TotalProductsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Total de Ventas:.
        /// </summary>
        public static string TotalSalesLabel {
            get {
                return ResourceManager.GetString("TotalSalesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario:.
        /// </summary>
        public static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
    }
}
